#!/bin/bash

# start os programs
sxhkd &
redshift &
picom &
dunst &
keepassxc &

# set the monitor layout
$HOME/bin/setmonitors.sh -o

#pkill wallpaperloop
#$HOME/bin/wallpaperloop.sh -s 1200 -r earthporn &
$HOME/bin/setwallpaper.sh

# start custom loopers
$HOME/bin/windowproperties.sh & # todo
$HOME/bin/batterynotify.sh &
$HOME/bin/bluetoothnotify.sh &

# enable lock
$HOME/bin/lock.sh -e

# bspwm settings
bspc config border_width	1
bspc config window_gap		0
bspc config bottom_padding	20

bspc config split_ratio		0.50

bspc config focus_follows_pointer	true
bspc config pointer_follows_monitor	true
bspc config ignore_ewmh_focus		true

bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config single_monocle	true

bspc rule -a 'Zathura' state=tiled
bspc rule -a '*:yad' state=floating
